In [13]:
import pandas as pd
import numpy as np
import scanpy as sc

## To AnnData Object

In [23]:
data = pd.read_csv("osd105/GLDS-105_rna_seq_Unnormalized_Counts.csv")
data = data.set_index("Unnamed: 0")
data

,Mmus_C57-6J_TA_FLT_Rep1_M23,Mmus_C57-6J_TA_FLT_Rep2_M24,Mmus_C57-6J_TA_FLT_Rep3_M25,Mmus_C57-6J_TA_FLT_Rep4_M26,Mmus_C57-6J_TA_FLT_Rep5_M27,Mmus_C57-6J_TA_FLT_Rep6_M28,Mmus_C57-6J_TA_GC_Rep1_M33,Mmus_C57-6J_TA_GC_Rep2_M34,Mmus_C57-6J_TA_GC_Rep3_M35,Mmus_C57-6J_TA_GC_Rep4_M36,Mmus_C57-6J_TA_GC_Rep5_M37,Mmus_C57-6J_TA_GC_Rep6_M38
Unnamed: 0,,,,,,,,,,,,
ENSMUSG00000000001,793.0,812.0,854.0,816.0,850.0,820.0,961.0,742.0,644.0,713.0,696.0,782.0
ENSMUSG00000000003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSMUSG00000000028,89.0,95.0,103.0,108.0,115.0,112.0,102.0,98.0,89.0,75.0,95.0,102.0
ENSMUSG00000000031,24947.0,22667.0,25050.0,34497.0,17978.0,20192.0,34797.0,31478.0,31941.0,29991.0,23981.0,31460.0
ENSMUSG00000000037,3.0,8.0,5.0,5.0,6.0,3.0,13.0,10.0,6.0,3.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...
ENSMUSG00000118389,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSMUSG00000118390,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSMUSG00000118391,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSMUSG00000118392,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ENSMUSG00000118393,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
adata = sc.AnnData(data.T, data.columns.to_frame(), data.index.to_frame())
adata.obs.columns = ['Sample ID']
adata.var.columns = ['Gene ID']

/explore/nobackup/people/kli3/.nccstmp/ipykernel_3553033/663925404.py:1: FutureWarning: X.dtype being converted to np.float32 from float64. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  adata = sc.AnnData(data.T, data.columns.to_frame(), data.index.to_frame())

In [26]:
adata.var

                               Gene ID
Unnamed: 0
ENSMUSG00000000001  ENSMUSG00000000001
ENSMUSG00000000003  ENSMUSG00000000003
ENSMUSG00000000028  ENSMUSG00000000028
ENSMUSG00000000031  ENSMUSG00000000031
ENSMUSG00000000037  ENSMUSG00000000037
...                                ...
ENSMUSG00000118389  ENSMUSG00000118389
ENSMUSG00000118390  ENSMUSG00000118390
ENSMUSG00000118391  ENSMUSG00000118391
ENSMUSG00000118392  ENSMUSG00000118392
ENSMUSG00000118393  ENSMUSG00000118393

[55536 rows x 1 columns]

## Ensembl to Gene ID

In [27]:
import pybiomart
import numpy as np

In [28]:
dataset = pybiomart.Dataset(name='mmusculus_gene_ensembl', host='http://www.ensembl.org')
mappings = dataset.query(attributes=['ensembl_gene_id', 'external_gene_name'])

In [29]:
def convert(e):
    x = mappings[mappings['Gene stable ID'] == e]
    if x.shape[0] != 0:
        return x['Gene name'].iloc[0]
    return np.NaN
gene_ids = adata.var_names.str.slice(stop=18).map(convert)
gene_ids

Index([        'Gnai3',          'Pbsn',         'Cdc45',           'H19',
               'Scml2',          'Apoh',          'Narf',          'Cav2',
                'Klf6',         'Scmh1',
       ...
       '9030625G05Rik',       'Gm50311',       'Gm50149',       'Gm50415',
             'Vmn1r64',       'Gm50246',       'Gm50102',       'Gm19519',
       '4930524O05Rik',       'Gm50426'],
      dtype='object', name='Unnamed: 0', length=55536)

In [30]:
adata.var_names = gene_ids

In [52]:
adata.var.index = adata.var_names.fillna("No GeneID")

In [31]:
adata.obs["y"] = ["FLT"] * 6 + ["GC"] * 6

In [53]:
adata.var

                          Gene ID
Unnamed: 0
Gnai3          ENSMUSG00000000001
Pbsn           ENSMUSG00000000003
Cdc45          ENSMUSG00000000028
H19            ENSMUSG00000000031
Scml2          ENSMUSG00000000037
...                           ...
Gm50246        ENSMUSG00000118389
Gm50102        ENSMUSG00000118390
Gm19519        ENSMUSG00000118391
4930524O05Rik  ENSMUSG00000118392
Gm50426        ENSMUSG00000118393

[55536 rows x 1 columns]

In [33]:
adata.obs

                                               Sample ID    y
Mmus_C57-6J_TA_FLT_Rep1_M23  Mmus_C57-6J_TA_FLT_Rep1_M23  FLT
Mmus_C57-6J_TA_FLT_Rep2_M24  Mmus_C57-6J_TA_FLT_Rep2_M24  FLT
Mmus_C57-6J_TA_FLT_Rep3_M25  Mmus_C57-6J_TA_FLT_Rep3_M25  FLT
Mmus_C57-6J_TA_FLT_Rep4_M26  Mmus_C57-6J_TA_FLT_Rep4_M26  FLT
Mmus_C57-6J_TA_FLT_Rep5_M27  Mmus_C57-6J_TA_FLT_Rep5_M27  FLT
Mmus_C57-6J_TA_FLT_Rep6_M28  Mmus_C57-6J_TA_FLT_Rep6_M28  FLT
Mmus_C57-6J_TA_GC_Rep1_M33    Mmus_C57-6J_TA_GC_Rep1_M33   GC
Mmus_C57-6J_TA_GC_Rep2_M34    Mmus_C57-6J_TA_GC_Rep2_M34   GC
Mmus_C57-6J_TA_GC_Rep3_M35    Mmus_C57-6J_TA_GC_Rep3_M35   GC
Mmus_C57-6J_TA_GC_Rep4_M36    Mmus_C57-6J_TA_GC_Rep4_M36   GC
Mmus_C57-6J_TA_GC_Rep5_M37    Mmus_C57-6J_TA_GC_Rep5_M37   GC
Mmus_C57-6J_TA_GC_Rep6_M38    Mmus_C57-6J_TA_GC_Rep6_M38   GC

In [42]:
adata.obs_names = adata.obs_names.str.split("_").str[-1]

In [54]:
adata.var

                          Gene ID
Unnamed: 0
Gnai3          ENSMUSG00000000001
Pbsn           ENSMUSG00000000003
Cdc45          ENSMUSG00000000028
H19            ENSMUSG00000000031
Scml2          ENSMUSG00000000037
...                           ...
Gm50246        ENSMUSG00000118389
Gm50102        ENSMUSG00000118390
Gm19519        ENSMUSG00000118391
4930524O05Rik  ENSMUSG00000118392
Gm50426        ENSMUSG00000118393

[55536 rows x 1 columns]

In [55]:
adata.write_h5ad("osd105/osd105_raw_ensembl_all_genes.h5ad")

## Select for genes with embedding

In [56]:
data = sc.read_h5ad('osd105/osd105_raw_ensembl_all_genes.h5ad')

/home/kli3/.conda/envs/scbert/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [58]:
embeddings_df = pd.read_csv("gene2vec/gene2vec_15117_compatible.csv")