In [4]:
import pandas as pd
import h5py
import scanpy as sc
from scipy import sparse

In [ ]:
data_preprocessed = sc.read_h5ad('recount3/preprocessed_data_with_metadata_2_8.h5ad')

In [82]:
embeddings_df = pd.read_csv("gene2vec/gene2vec_24447.csv")

In [ ]:
data_preprocessed.var.index = data_preprocessed.var.index.str.lower()

In [114]:
data_preprocessed.var

                         Ensemble ID
no geneid       ENSMUSG00000079800.2
no geneid-1     ENSMUSG00000095092.1
no geneid-2     ENSMUSG00000079192.2
no geneid-3     ENSMUSG00000079794.2
no geneid-4     ENSMUSG00000094799.1
...                              ...
mid1-ps1        ENSMUSG00000095134.2
gm47283         ENSMUSG00000096768.8
gm21748         ENSMUSG00000096850.1
gm21742         ENSMUSG00000099871.1
no geneid-3181               project

[55422 rows x 1 columns]

In [86]:
embeddings_df = embeddings_df.set_index('0')
embeddings_df

,1,2,3,4,5,6,7,8,9,10,...,191,192,193,194,195,196,197,198,199,200
0,,,,,,,,,,,,,,,,,,,,,
PLAC4,-0.032111,0.005355,-0.001208,0.392700,0.027191,0.057858,-0.065911,0.256802,0.043661,0.081228,...,0.179668,0.199858,-0.044920,0.095846,0.041332,-0.147439,0.239312,-0.183174,-0.264830,0.104818
RPS2P45,-0.433589,0.383065,0.154259,-0.044726,0.406748,0.089424,0.186105,-0.038986,0.245488,-0.712083,...,0.079383,-0.028575,0.263809,0.177087,-0.015819,0.120731,-0.219403,0.199372,0.101292,-0.054681
C3orf18,0.030009,-0.283322,0.213689,0.084640,-0.012634,-0.288767,-0.004061,-0.089572,0.249219,0.164836,...,0.037768,0.328689,0.064318,0.026143,0.005801,-0.185695,0.067693,-0.246346,-0.120931,0.157672
C6orf226,0.029573,-0.058847,-0.297716,0.257432,0.062723,0.071785,-0.079403,0.420420,0.219320,0.316385,...,0.243931,-0.075696,0.092758,0.093465,-0.191904,-0.286557,-0.140394,-0.159963,-0.223003,0.250665
CISD3,0.148815,-0.100394,0.139844,-0.156749,-0.000815,0.115267,0.101778,0.158580,0.287842,0.049861,...,0.227863,0.086968,0.062115,0.314489,-0.148824,-0.121338,-0.245106,0.247893,-0.034497,0.038109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LOC284219,-0.097413,0.206977,0.274137,-0.052645,-0.163830,0.080587,0.147385,-0.081156,-0.100284,0.190910,...,0.516521,-0.356231,0.259438,-0.353476,-0.510408,0.158663,-0.378703,-0.184715,0.041767,0.065761
KRTAP21-1,0.093780,-0.661438,0.342262,-0.742463,-0.402170,0.172066,1.039949,-0.706364,1.170597,-0.120575,...,-0.046443,0.347276,1.131234,0.249182,0.902638,0.147042,0.445153,-0.163675,-0.148416,0.195759
PHBP8,-0.491280,-0.335584,-0.454166,-0.134393,-0.455670,-0.137623,-0.335810,-0.065315,-0.172522,-0.110279,...,0.743257,0.116302,0.027702,-0.351308,0.163348,-0.089611,-0.345655,-0.071142,0.027078,0.223668
KCNE1L,-0.103615,0.133627,-0.156624,0.134105,-0.226790,-0.120270,0.161322,-0.165074,-0.041661,-0.313059,...,0.022152,-0.699078,0.035016,-0.788035,-0.045039,-0.304939,0.130196,0.361877,0.190919,0.649156
LOC101928725,-0.179048,0.241712,-0.074082,-0.137115,0.160695,-0.034816,0.205781,0.063766,-0.600309,-0.225615,...,0.101723,0.184042,0.120395,0.157748,-0.170004,0.337413,0.421538,-0.103381,-0.307587,-0.053007

In [93]:
embeddings_df.loc["NDUFAF4",:]

1      0.142516
2      0.032082
3      0.148707
4      0.037182
5      0.436337
         ...
196    0.213378
197   -0.196731
198    0.210595
199    0.016922
200   -0.088217
Name: NDUFAF4, Length: 200, dtype: float64

In [18]:
embeddings_df.index = embeddings_df.index.str.lower()

In [47]:
data_preprocessed[:, "cisd3"]

View of AnnData object with n_obs Ã— n_vars = 410235 Ã— 1
    obs: 'Sample ID', 'project', 'pattern.predict.type', 'study', 'n_genes'
    var: 'Ensemble ID'
    uns: 'log1p'

In [49]:
len(set(embeddings_df.index))

24445

In [29]:
import numpy as np

In [34]:
intersection = np.intersect1d(embeddings_df.index, data_preprocessed.var.index)

In [74]:
len(intersection)

15117

In [62]:
data_preprocessed.var_names_make_unique()

In [63]:
data_preprocessed.var

                         Ensemble ID
no geneid       ENSMUSG00000079800.2
no geneid-1     ENSMUSG00000095092.1
no geneid-2     ENSMUSG00000079192.2
no geneid-3     ENSMUSG00000079794.2
no geneid-4     ENSMUSG00000094799.1
...                              ...
mid1-ps1        ENSMUSG00000095134.2
gm47283         ENSMUSG00000096768.8
gm21748         ENSMUSG00000096850.1
gm21742         ENSMUSG00000099871.1
no geneid-3181               project

[55422 rows x 1 columns]

In [64]:
data_preprocessed_subset = data_preprocessed[:, intersection]

In [115]:
data_preprocessed_subset

View of AnnData object with n_obs Ã— n_vars = 410235 Ã— 15117
    obs: 'Sample ID', 'project', 'pattern.predict.type', 'study', 'n_genes'
    var: 'Ensemble ID'
    uns: 'log1p'

In [65]:
data_preprocessed_subset.var

                  Ensemble ID
a1bg     ENSMUSG00000022347.8
a1cf     ENSMUSG00000052595.8
a2m      ENSMUSG00000030111.9
a2ml1    ENSMUSG00000047228.9
a4galt  ENSMUSG00000047878.13
...                       ...
zyg11a  ENSMUSG00000034645.14
zyg11b   ENSMUSG00000034636.9
zyx     ENSMUSG00000029860.16
zzef1   ENSMUSG00000055670.14
zzz3    ENSMUSG00000039068.16

[15117 rows x 1 columns]

In [76]:
embedding_sub = embeddings_df.loc[intersection,:]

In [108]:
embedding_sub= embedding_sub.loc[~embedding_sub.index.duplicated(keep='last'),:]

In [111]:
all(embedding_sub.index == data_preprocessed_subset.var.index)

True

In [117]:
embedding_sub.to_csv("gene2vec/gene2vec_15117_compatible21823.csv")

In [118]:
np.save("gene2vec/gene2vec_15117_compatible21823.npy", embedding_sub.to_numpy())

In [116]:
data_preprocessed_subset.write_h5ad("recount3/preprocessed_mouse_gene2vec_compatible21823.h5ad")